### ISSUE TITLE
New Logo Request at Simio

### ISSUE THREAD

**Issue by EricSimio** [onnx/onnx.github.io#110]
Hello,

I am the VP of Marketing at Simio and is requesting to be added to the Framework and converter category.

To have your logo displayed, submit a PR to https://github.com/onnx/onnx.github.io with the following:

Text of the PR must include written permission indicating the logo can be used on the onnx.ai website as well as in presentations showing ONNX Member Companies
 - here is the press release: https://apnews.com/press-release/globe-newswire/technology-business-software-bc8e5c1d6f64553caa4497983d3675f0
you have our permission to use the logo

A high quality logo file with transparent background needs to be committed in the "assets" directory. The image file should be 300dpi (best if physical printing is ever required) or a vector file which can be saved in any resolution.
- Done
![logo_transparent](https://user-images.githubusercontent.com/93614885/145897955-3dd33384-b8fe-4dea-86b2-e5fa5abe8c26.png)

The URL of your company or product web page. Ideally the page mentions ONNX.
-  https://www.simio.com/applications/industry-40/Artificial-Intelligence.php

**Comment by prasanthpul** [comment]
We missed this earlier - will work on it now

**Comment by prasanthpul** [comment]
Thanks for your patience on the unusually long delay. 
The logo has now been added to the supported pages!

**Comment by EricSimio** [comment]
Hello All,

I am just checking in.  Do you need anything else from me?

Eric

From: Prasanth Pulavarthi ***@***.***>
Date: Friday, March 18, 2022 at 12:46 PM
To: onnx/onnx.github.io ***@***.***>
Cc: Eric Howard ***@***.***>, Author ***@***.***>
Subject: Re: [onnx/onnx.github.io] New Logo Request at Simio (Issue #110)

We missed this earlier - will work on it now

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fonnx%2Fonnx.github.io%2Fissues%2F110%23issuecomment-1072594228&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=olZBYlG4leoIwfaOpToJT17eJzDD%2F7773mMlLC9PXGM%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKHGJKFO5ALQ56G47G7YHDVASXO5ANCNFSM5J7KU7DA&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VDo3f311q1Th4iX66AEs9mXs7sYmF%2FvIw7PZu3LUVcw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7%2BrK3Ufp%2BfC1Vg4m%2BFKBUP%2FgktcL5QK2IemPH5Hsvrc%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jlebil3XFjAiDfjfo6HLTalcdAWN3WYo98tVHrL6CL8%3D&reserved=0>.

**Comment by EricSimio** [comment]
Hello,

Let me know what you might need from me

Eric

From: Prasanth Pulavarthi ***@***.***>
Date: Friday, March 18, 2022 at 12:46 PM
To: onnx/onnx.github.io ***@***.***>
Cc: Eric Howard ***@***.***>, Author ***@***.***>
Subject: Re: [onnx/onnx.github.io] New Logo Request at Simio (Issue #110)

We missed this earlier - will work on it now

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fonnx%2Fonnx.github.io%2Fissues%2F110%23issuecomment-1072594228&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=olZBYlG4leoIwfaOpToJT17eJzDD%2F7773mMlLC9PXGM%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKHGJKFO5ALQ56G47G7YHDVASXO5ANCNFSM5J7KU7DA&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VDo3f311q1Th4iX66AEs9mXs7sYmF%2FvIw7PZu3LUVcw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7%2BrK3Ufp%2BfC1Vg4m%2BFKBUP%2FgktcL5QK2IemPH5Hsvrc%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cehoward%40simio.com%7C8ae062636ed94ba2ea3a08da08fedfaa%7Ca0b1816e92b14d768b9b727584179ec1%7C1%7C0%7C637832188034222679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jlebil3XFjAiDfjfo6HLTalcdAWN3WYo98tVHrL6CL8%3D&reserved=0>.
