### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by andife** [onnx/onnx.github.io#122]
1) 
The documentation 

http://onnx.ai/onnx-mlir/

contains a link to 
http://onnx.ai/onnx-mlir/HowToAddAnOperation.html
which is invalid now

The page was removed 19 Jan 2022
https://github.com/onnx/onnx-mlir/commit/184d1a65eb208ab44865df88beaabfab20c8c111

Is there a fixed interval when the doc is updated there?

2) The link to https://www.siemens.com/plm/simcenter-amesim
from https://onnx.ai/supported-tools.html does also not work.

**Comment by AlexandreEichenberger** [comment]
Thanks, this link comes from the onnx-mlir repo. Will open an issue there.

**Comment by prasanthpul** [comment]
@AlexandreEichenberger  once opened there, please close this

**Comment by AlexandreEichenberger** [comment]
fixed
