### ISSUE TITLE
documentation page from ONNX runtime export on customvision.ai doe snto work 

### ISSUE THREAD

**Issue by initmahesh** [onnx/onnx.github.io#46]
i clicked on ONNX docuemtation page on customvision.ai and it errored out for me as below 
![image](https://user-images.githubusercontent.com/21267354/77812927-120a6b00-7062-11ea-9b6e-02cbc90d88d8.png)

**Comment by prasanthpul** [comment]
You can get to the info you are looking for at: http://onnx.ai/get-started.html

Can you file a bug with the customvision.ai owners to update the link?

There was never a page onnx.ai/getting-started (there used to be a onnx.ai/getting-started.html) so this link was always wrong.
