### ISSUE TITLE
add deepC as part of ONNX compiler

### ISSUE THREAD

**Issue by srohit0** [onnx/onnx.github.io#93]
Our repository is at https://github.com/ai-techsystems/deepC. 

deepC is a vendor independent deep learning library, compiler and inference framework supporting ONNX natively. It is designed for small form-factor devices including μControllers, IoT and Edge devices.

Our logo is at https://www.ai-tech.systems/wp-content/uploads/2020/04/AITS_logo_white-1-160x90.png . Let us know, if you need a different resolution.

regards,
-Rohit

**Comment by srohit0** [comment]
When would I see the update on this? Idea of timeline would be helpful.

Thanks

**Comment by srohit0** [comment]
Bringing it up again for some attention. Requesting ETA from the team.

**Comment by prasanthpul** [comment]
sorry for the delay. will work on creating a PR for this
